### ISSUE TITLE
Save-Issue in parent-child-situation when deleting a record on child form

### ISSUE THREAD

**Issue by philippr71** [Servoy/svyBase#3]
Hi

We have the following issue:

Our settings:
	
policy.setBatchScopePolicy(scopes.svyCRUDManager.BATCH_SCOPE_POLICY.ALL);
policy.setRecordLockingPolicy(scopes.svyCRUDManager.RECORD_LOCKING_POLICY.NONE)
policy.setValidationPolicy(scopes.svyCRUDManager.VALIDATION_POLICY.CONTINUOUS);
policy.setFormHidePolicy(scopes.svyCRUDManager.FORM_HIDE_POLICY.ALLOW_WHEN_EDITING);

As an addition for parent forms: policy.setRecordSelectionPolicy(scopes.svyCRUDManager.RECORD_SELECTION_POLICY.PREVENT_WHEN_EDITING);

and for child forms:
policy.setRecordSelectionPolicy(scopes.svyCRUDManager.RECORD_SELECTION_POLICY.ALLOW_WHEN_EDITING);

Situation: we have a parent form and a child form. Save of all records (parent and child forms) always happens on the parent form.

We do the following steps:

- Add a new record on the parent form (don't save)
- Add a new record on the child form (don't save)
- Delete the record on the child form

This leads to the situation that the record on the parent form is saved (not in create-mode anymore)! The record is not stored in the database but it looks to the user as the record is stored, even if validation failed. So the user must reload the parent form data or delete the record in parent form.

Expectation: if the user deletes a record in the child form, the parent form must  remain in its state!

Thanks in advance!

Best
Roland

**Comment by paronne** [comment]
Hi Roland,

thanks for reporting the issue; a fix is now available on the latest source code.
You can apply the same changes of the commit f34be1683c67be2df8a454381e40fff3a5fb18c2
